// =================================================================================
// ARCHIVO CENTRAL DE CONSTANTES Y MAPEOS
// =================================================================================

/**
 * Mapeo para el MAPA: Traduce los nombres que vienen del archivo GeoJSON
 * a las claves que usamos en nuestro objeto `todosLosBilletes`.
 * Clave: Nombre en inglés del GeoJSON. Valor: Clave usada en nuestros datos.
 */
export const mapaNombres: Record<string, string> = {
  // --- Mapeos Clave Corregidos ---
  "Cameroon": "Camerun",
  "Guinea-Bisau": "Guinea-Bisáu", // <-- CORRECCIÓN APLICADA AQUÍ
  "Western Sahara": "Sahara Occidental",
  "W. Sahara": "Sahara Occidental",
  "United States of America": "USA",
  "United States": "USA",
  "Falkland Is.": "Islas Malvinas",
  "El Salvador": "ElSalvador",
  "South Africa": "Sudafrica",
  "Russian Federation": "Rusia",
  "Russia": "Rusia",
  "Czech Rep.": "Republica Checa",
  "Czechia": "Republica Checa",
  "Dominican Rep.": "Republica Dominicana",
  "Dem. Rep. Congo": "Republica Democratica del Congo",
  "Congo": "Republica del Congo",
  "Central African Rep.": "Republica Centroafricana",
  "Eq. Guinea": "Guinea Ecuatorial",  
  "United Kingdom": "Inglaterra",
  "Netherlands": "Países Bajos",
  "Côte d'Ivoire": "Costa de Marfil",
  "S. Korea": "Corea del Sur",
  "N. Korea": "Corea del Norte",
  "Bosnia and Herz.": "Bosnia",
  "North Macedonia": "Macedonia",
  "United Arab Emirates": "Emiratos Arabes Unidos",
  "Saudi Arabia": "Arabia Saudita",
  "South Sudan": "Sudan del Sur",
  "New Zealand": "Nueva Zelanda",
  "Solomon Is.": "Islas Salomon",
  "Papua New Guinea": "Papua Nueva Guinea",
  "Sri Lanka": "Sri Lanka",
  "Timor-Leste": "TimorOriental" 
};

/**
 * Mapeo para la INTERFAZ: Traduce nuestras claves de datos internas
 * a un nombre legible y en español para mostrar en el selector y los títulos.
 * Clave: Clave usada en nuestros datos. Valor: Nombre a mostrar al usuario.
 */
export const nombresPaises: Record<string, string> = {
  "USA": "Estados Unidos",
  "Afganistan": "Afganistán",
  "Albania": "Albania",
  "Alemania": "Alemania",
  "Angola": "Angola",
  "Arabia Saudita": "Arabia Saudita",
  "Argelia": "Argelia",
  "Argentina": "Argentina",
  "Armenia": "Armenia",
  "Australia": "Australia",
  "Austria": "Austria",
  "Azerbaiyan": "Azerbaiyán",
  "Bahamas": "Bahamas",
  "Bangladesh": "Bangladesh",
  "Belgica": "Bélgica",
  "Belice": "Belice",
  "Benin": "Benín",
  "Bielorrusia": "Bielorrusia",
  "Bolivia": "Bolivia",
  "Bosnia": "Bosnia y Herzegovina",
  "Botswana": "Botsuana",
  "Brasil": "Brasil",
  "Bulgaria": "Bulgaria",
  "Burkina Faso": "Burkina Faso",
  "Burundi": "Burundi",
  "Butan": "Bután",
  "Cabo Verde": "Cabo Verde",
  "Nueva Caledonia": "Nueva Caledonia",
  "Camboya": "Camboya",
  "Camerun": "Camerún",
  "Canada": "Canadá",
  "Chad": "Chad",
  "Chile": "Chile",
  "China": "China",
  "Chipre": "Chipre",
  "Colombia": "Colombia",
  "Comoros": "Comoras",
  "Corea del Norte": "Corea del Norte",
  "Corea del Sur": "Corea del Sur",
  "Costa de Marfil": "Costa de Marfil",
  "CostaRica": "Costa Rica",
  "Croacia": "Croacia",
  "Cuba": "Cuba",
  "Djibouti": "Yibuti",
  "Dinamarca": "Dinamarca",
  "Ecuador": "Ecuador",
  "Egipto": "Egipto",
  "ElSalvador": "El Salvador",
  "Emiratos Arabes Unidos": "Emiratos Árabes Unidos",
  "Eslovaquia": "Eslovaquia",
  "Eslovenia": "Eslovenia",
  "España": "España",
  "Estonia": "Estonia",
  "Fiji": "Fiyi",
  "Filipinas": "Filipinas",
  "Finlandia": "Finlandia",
  "Francia": "Francia",
  "Gabon": "Gabón",
  "Gambia": "Gambia",
  "Georgia": "Georgia",
  "Ghana": "Ghana",
  "Grecia": "Grecia",
  "Groenlandia": "Groenlandia",
  "Guatemala": "Guatemala",
  "Guinea": "Guinea",
  "Guinea Bissau": "Guinea Bissau",
  "Guinea Ecuatorial": "Guinea Ecuatorial",
  "Guyana": "Guyana",
  "Guyana Francesa": "Guayana Francesa",
  "Haiti": "Haití",
  "Honduras": "Honduras",
  "Hong Kong": "Hong Kong",
  "Hungria": "Hungría",
  "India": "India",
  "Indonesia": "Indonesia",
  "Inglaterra": "Inglaterra (Reino Unido)",
  "Irak": "Irak",
  "Iran": "Irán",
  "Irlanda": "Irlanda",
  "Islandia": "Islandia",
  "Islas Malvinas": "Islas Malvinas",
  "Islas Salomon": "Islas Salomón",
  "Israel": "Israel",
  "Italia": "Italia",
  "Jamaica": "Jamaica",
  "Japon": "Japón",
  "Jordania": "Jordania",
  "Kazajstan": "Kazajistán",
  "Kirguistan": "Kirguistán",
  "Kuwait": "Kuwait",
  "Laos": "Laos",
  "Lesoto": "Lesoto",
  "Letonia": "Letonia",
  "Libano": "Líbano",
  "Liberia": "Liberia",
  "Libia": "Libia",
  "Lituania": "Lituania",
  "Luxemburgo": "Luxemburgo",
  "Macedonia": "Macedonia del Norte",
  "Madagascar": "Madagascar",
  "Malasia": "Malasia",
  "Mali": "Mali",
  "Malta": "Malta",
  "Marruecos": "Marruecos",
  "Mauritania": "Mauritania",
  "Mexico": "México",
  "Moldavia": "Moldavia",
  "Mongolia": "Mongolia",
  "Montenegro": "Montenegro",
  "Myanmar": "Myanmar",
  "Nepal": "Nepal",
  "Nicaragua": "Nicaragua",
  "Niger": "Níger",
  "Nigeria": "Nigeria",
  "Noruega": "Noruega",
  "Nueva Zelanda": "Nueva Zelanda",
  "Oman": "Omán",
  "Países Bajos": "Países Bajos",
  "Pakistan": "Pakistán",
  "Panama": "Panamá",
  "Papua Nueva Guinea": "Papúa Nueva Guinea",
  "Paraguay": "Paraguay",
  "Peru": "Perú",
  "Polonia": "Polonia",
  "Portugal": "Portugal",
  "PuertoRico": "Puerto Rico",
  "Qatar": "Qatar",
  "Republica Checa": "República Checa",
  "Republica del Congo": "República del Congo",
  "Republica Democratica del Congo": "Rep. Dem. del Congo",
  "Republica Dominicana": "República Dominicana",
  "Republica Centroafricana": "República Centroafricana",
  "Rumania": "Rumanía",
  "Rusia": "Rusia",
  "Sahara Occidental": "Sahara Occidental",
  "Senegal": "Senegal",
  "Serbia": "Serbia",
  "Sierra Leona": "Sierra Leona",
  "Singapur": "Singapur",
  "Siria": "Siria",
  "SriLanka": "Sri Lanka",
  "Sudafrica": "Sudáfrica",
  "Sudan": "Sudán",
  "Sudan del Sur": "Sudán del Sur",
  "Suecia": "Suecia",
  "Suiza": "Suiza",
  "Surinam": "Surinam",
  "Tailandia": "Tailandia",
  "Taiwan": "Taiwán",
  "Tanzania": "Tanzania",
  "Tayikistan": "Tayikistán",
  "Tierras Australes y Antárticas Francesas": "Tierras Australes y Antárticas Francesas",
  "TimorOriental": "Timor Oriental",
  "Togo": "Togo",
  "Trinidad y Tobago": "Trinidad y Tobago",
  "Tunez": "Túnez",
  "Turkmenistan": "Turkmenistán",
  "Turquia": "Turquía",
  "Ucrania": "Ucrania",
  "Uganda": "Uganda",
  "Uruguay": "Uruguay",
  "Uzbekistan": "Uzbekistán",
  "Vanuatu": "Vanuatu",
  "Venezuela": "Venezuela",
  "Vietnam": "Vietnam",
  "Yemen": "Yemen",
  "Zambia": "Zambia",
  "Zimbabwe": "Zimbabue"
};

// Países que usan el Euro
export const paisesEuro = [
  "Alemania", "Austria", "Belgica", "Chipre", "Croacia", "Eslovaquia", 
  "Eslovenia", "España", "Estonia", "Finlandia", "Francia", "Grecia", 
  "Irlanda", "Italia", "Letonia", "Lituania", "Luxemburgo", "Malta", 
  "Países Bajos", "Portugal", "Guyana Francesa", "Tierras Australes y Antárticas Francesas", "Montenegro"
   ];

// Países que usan el Franco CFA
export const paisesCFA = [
  "Benin", "Burkina Faso", "Costa de Marfil", "Guinea Bissau", 
  "Mali", "Niger", "Senegal", "Togo", "Camerun", "Chad", 
  "Gabon", "Guinea Ecuatorial", "Republica del Congo", 
  "Republica Centroafricana"
];

// Mapeo de países a códigos ISO (se mantiene por si se usa en el futuro)
export const codigosPaises: Record<string, string> = {
  "Afganistan": "AF", "Albania": "AL", "Alemania": "DE", "Angola": "AO", 
  "Arabia Saudita": "SA", "Argelia": "DZ", "Argentina": "AR", "Armenia": "AM", 
  "Australia": "AU", "Austria": "AT", "Azerbaiyan": "AZ", "Bahamas": "BS",
  "Bangladesh": "BD", "Belgica": "BE", "Belice": "BZ", "Benin": "BJ", 
  "Bielorrusia": "BY", "Bolivia": "BO", "Bosnia": "BA", "Botswana": "BW", 
  "Brasil": "BR", "Bulgaria": "BG", "Burkina Faso": "BF", "Burundi": "BI", 
  "Butan": "BT", "Cabo Verde": "CV", "Camboya": "KH", "Camerun": "CM", 
  "Canada": "CA", "Chad": "TD", "Chile": "CL", "China": "CN", "Chipre": "CY", 
  "Colombia": "CO", "Comoros": "KM", "Corea del Norte": "KP", "Corea del Sur": "KR", 
  "Costa de Marfil": "CI", "CostaRica": "CR", "Croacia": "HR", "Cuba": "CU", 
  "Dinamarca": "DK", "Ecuador": "EC", "Egipto": "EG", "ElSalvador": "SV", 
  "Emiratos Arabes Unidos": "AE", "Eslovaquia": "SK", "Eslovenia": "SI", 
  "España": "ES", "USA": "US", "Estonia": "EE", "Etiopia": "ET", 
  "Filipinas": "PH", "Finlandia": "FI", "Francia": "FR", "Gabon": "GA", 
  "Gambia": "GM", "Georgia": "GE", "Ghana": "GH", "Grecia": "GR", 
  "Groenlandia": "GL", "Guatemala": "GT", "Guinea": "GN", "Guinea-Bisau": "GW", 
  "Guinea Ecuatorial": "GQ", "Guyana": "GY", "Guyana Francesa": "GF", "Haiti": "HT", 
  "Honduras": "HN", "Hong Kong": "HK", "Hungria": "HU", "India": "IN", 
  "Indonesia": "ID", "Inglaterra": "GB", "Irak": "IQ", "Iran": "IR", "Irlanda": "IE", 
  "Islandia": "IS", "Islas Malvinas": "FK", "Islas Salomon": "SB", "Israel": "IL", 
  "Italia": "IT", "Jamaica": "JM", "Japon": "JP", "Jordania": "JO", "Kazajstan": "KZ", 
  "Kirguistan": "KG", "Kuwait": "KW", "Laos": "LA", "Letonia": "LV", "Libano": "LB", 
  "Liberia": "LR", "Libia": "LY", "Lituania": "LT", "Luxemburgo": "LU", 
  "Macedonia": "MK", "Madagascar": "MG", "Malasia": "MY", "Malawi": "MW", 
  "Mali": "ML", "Malta": "MT", "Marruecos": "MA", "Mauritania": "MR", 
  "Mexico": "MX", "Moldavia": "MD", "Mongolia": "MN", "Montenegro": "ME", 
  "Myanmar": "MM", "Nepal": "NP", "Nicaragua": "NI", "Niger": "NE", "Nigeria": "NG", 
  "Noruega": "NO", "Nueva Caledonia": "NC", "Nueva Zelanda": "NZ", "Oman": "OM", "Países Bajos": "NL", 
  "Pakistan": "PK", "Panama": "PA", "Papua Nueva Guinea": "PG", "Paraguay": "PY", 
  "Peru": "PE", "Polonia": "PL", "Portugal": "PT", "PuertoRico": "PR", "Qatar": "QA", 
  "Republica Checa": "CZ", "Republica del Congo": "CG", "Republica Democratica del Congo": "CD", 
  "Republica Dominicana": "DO", "Republica Centroafricana": "CF", "Rumania": "RO", 
  "Rusia": "RU", "Sahara Occidental": "EH", "Senegal": "SN", "Serbia": "RS", 
  "Sierra Leona": "SL", "Singapur": "SG", "Siria": "SY", "Somalia": "SO", 
  "SriLanka": "LK", "Sudafrica": "ZA", "Sudan": "SD", "Sudan del Sur": "SS", 
  "Suecia": "SE", "Suiza": "CH", "Surinam": "SR", "Tailandia": "TH", "Taiwan": "TW", 
  "Tanzania": "TZ", "Tayikistan": "TJ", "TimorOriental": "TL", "Togo": "TG", 
  "Trinidad y Tobago": "TT", "Tunez": "TN", "Turkmenistan": "TM", "Turquia": "TR", 
  "Ucrania": "UA", "Uganda": "UG", "Uruguay": "UY", "Uzbekistan": "UZ", 
  "Venezuela": "VE", "Vietnam": "VN", "Yemen": "YE", "Zambia": "ZM", "Zimbabwe": "ZW"
};

/**
 * Coordenadas para centrar el mapa en un país específico.
 * Clave: La misma clave usada en nuestros datos (ej: "USA", "Argentina").
 * Valor: { lat: number, lng: number, zoom: number }
 */
export const coordenadasPaises: Record<string, { lat: number; lng: number; zoom: number }> = {
  "USA": { lat: 37.09, lng: -95.71, zoom: 4 },
  "Afganistan": { lat: 33.93, lng: 67.70, zoom: 5 },
  "Albania": { lat: 41.15, lng: 20.16, zoom: 7 },
  "Alemania": { lat: 51.16, lng: 10.45, zoom: 5 },
  "Angola": { lat: -11.20, lng: 17.87, zoom: 5 },
  "Arabia Saudita": { lat: 23.88, lng: 45.07, zoom: 5 },
  "Argelia": { lat: 28.03, lng: 1.65, zoom: 5 },
  "Argentina": { lat: -38.41, lng: -63.61, zoom: 4 },
  "Armenia": { lat: 40.06, lng: 45.03, zoom: 8 },
  "Australia": { lat: -25.27, lng: 133.77, zoom: 4 },
  "Austria": { lat: 47.51, lng: 14.55, zoom: 6 },
  "Azerbaiyan": { lat: 40.14, lng: 47.57, zoom: 7 },
  "Bahamas": { lat: 25.03, lng: -77.39, zoom: 7 },
  "Bangladesh": { lat: 23.68, lng: 90.35, zoom: 7 },
  "Belgica": { lat: 50.85, lng: 4.35, zoom: 8 },
  "Belice": { lat: 17.18, lng: -88.49, zoom: 8 },
  "Benin": { lat: 9.30, lng: 2.31, zoom: 7 },
  "Bielorrusia": { lat: 53.70, lng: 27.95, zoom: 6 },
  "Bolivia": { lat: -16.29, lng: -63.58, zoom: 5 },
  "Bosnia": { lat: 43.91, lng: 17.67, zoom: 7 },
  "Botswana": { lat: -22.32, lng: 24.68, zoom: 6 },
  "Brasil": { lat: -14.23, lng: -51.92, zoom: 4 },
  "Bulgaria": { lat: 42.73, lng: 25.48, zoom: 7 },
  "Burkina Faso": { lat: 12.23, lng: -1.56, zoom: 6 },
  "Burundi": { lat: -3.37, lng: 29.91, zoom: 8 },
  "Butan": { lat: 27.51, lng: 90.43, zoom: 8 },
  "Cabo Verde": { lat: 16.53, lng: -23.04, zoom: 7 },
  "Camboya": { lat: 12.56, lng: 104.99, zoom: 7 },
  "Camerun": { lat: 7.36, lng: 12.35, zoom: 6 },
  "Canada": { lat: 56.13, lng: -106.34, zoom: 3 },
  "Chad": { lat: 15.45, lng: 18.73, zoom: 5 },
  "Chile": { lat: -35.67, lng: -71.54, zoom: 5 },
  "China": { lat: 35.86, lng: 104.19, zoom: 4 },
  "Chipre": { lat: 35.12, lng: 33.42, zoom: 9 },
  "Colombia": { lat: 4.57, lng: -74.29, zoom: 5 },
  "Comoros": { lat: -11.87, lng: 43.87, zoom: 9 },
  "Corea del Norte": { lat: 40.33, lng: 127.51, zoom: 7 },
  "Corea del Sur": { lat: 35.90, lng: 127.76, zoom: 7 },
  "Costa de Marfil": { lat: 7.53, lng: -5.54, zoom: 6 },
  "CostaRica": { lat: 9.74, lng: -83.75, zoom: 7 },
  "Croacia": { lat: 45.1, lng: 15.2, zoom: 7 },
  "Cuba": { lat: 21.52, lng: -77.78, zoom: 7 },
  "Dinamarca": { lat: 56.26, lng: 9.5, zoom: 7 },
  "Ecuador": { lat: -1.83, lng: -78.18, zoom: 6 },
  "Egipto": { lat: 26.82, lng: 30.8, zoom: 5 },
  "ElSalvador": { lat: 13.79, lng: -88.89, zoom: 8 },
  "Emiratos Arabes Unidos": { lat: 23.42, lng: 53.84, zoom: 7 },
  "Eslovaquia": { lat: 48.66, lng: 19.69, zoom: 7 },
  "Eslovenia": { lat: 46.15, lng: 14.99, zoom: 8 },
  "España": { lat: 40.46, lng: -3.74, zoom: 6 },
  "Estonia": { lat: 58.59, lng: 25.01, zoom: 7 },
  "Filipinas": { lat: 12.87, lng: 121.77, zoom: 5 },
  "Finlandia": { lat: 61.92, lng: 25.74, zoom: 5 },
  "Francia": { lat: 46.22, lng: 2.21, zoom: 5 },
  "Gabon": { lat: -0.8, lng: 11.6, zoom: 7 },
  "Gambia": { lat: 13.44, lng: -15.31, zoom: 8 },
  "Georgia": { lat: 42.31, lng: 43.35, zoom: 7 },
  "Ghana": { lat: 7.94, lng: -1.02, zoom: 7 },
  "Grecia": { lat: 39.07, lng: 21.82, zoom: 6 },
  "Groenlandia": { lat: 71.7, lng: -42.6, zoom: 4 },
  "Guatemala": { lat: 15.78, lng: -90.23, zoom: 7 },
  "Guinea": { lat: 9.94, lng: -9.69, zoom: 7 },
  "Guinea Bissau": { lat: 11.8, lng: -15.18, zoom: 8 },
  "Guinea Ecuatorial": { lat: 1.65, lng: 10.26, zoom: 8 },
  "Guyana": { lat: 4.86, lng: -58.93, zoom: 7 },
  "Guyana Francesa": { lat: 3.93, lng: -53.12, zoom: 7 },
  "Haiti": { lat: 18.97, lng: -72.28, zoom: 8 },
  "Honduras": { lat: 15.19, lng: -86.24, zoom: 7 },
  "Hong Kong": { lat: 22.31, lng: 114.16, zoom: 10 },
  "Hungria": { lat: 47.16, lng: 19.5, zoom: 7 },
  "India": { lat: 20.59, lng: 78.96, zoom: 4 },
  "Indonesia": { lat: -0.78, lng: 113.92, zoom: 4 },
  "Inglaterra": { lat: 55.37, lng: -3.43, zoom: 5 },
  "Irak": { lat: 33.22, lng: 43.67, zoom: 6 },
  "Iran": { lat: 32.42, lng: 53.68, zoom: 5 },
  "Irlanda": { lat: 53.41, lng: -8.24, zoom: 7 },
  "Islandia": { lat: 64.96, lng: -19.02, zoom: 6 },
  "Islas Malvinas": { lat: -51.79, lng: -59.52, zoom: 7 },
  "Islas Salomon": { lat: -9.64, lng: 160.15, zoom: 7 },
  "Israel": { lat: 31.04, lng: 34.85, zoom: 7 },
  "Italia": { lat: 41.87, lng: 12.56, zoom: 5 },
  "Jamaica": { lat: 18.1, lng: -77.29, zoom: 9 },
  "Japon": { lat: 36.2, lng: 138.25, zoom: 5 },
  "Jordania": { lat: 30.58, lng: 36.23, zoom: 7 },
  "Kazajstan": { lat: 48.01, lng: 66.92, zoom: 4 },
  "Kirguistan": { lat: 41.2, lng: 74.76, zoom: 6 },
  "Kuwait": { lat: 29.31, lng: 47.48, zoom: 8 },
  "Laos": { lat: 19.85, lng: 102.49, zoom: 6 },
  "Lesoto": { lat: -29.61, lng: 28.24, zoom: 7 },
  "Letonia": { lat: 56.87, lng: 24.6, zoom: 7 },
  "Libano": { lat: 33.85, lng: 35.86, zoom: 9 },
  "Liberia": { lat: 6.42, lng: -9.42, zoom: 7 },
  "Libia": { lat: 26.33, lng: 17.22, zoom: 5 },
  "Lituania": { lat: 55.16, lng: 23.88, zoom: 7 },
  "Luxemburgo": { lat: 49.81, lng: 6.12, zoom: 9 },
  "Macedonia": { lat: 41.6, lng: 21.74, zoom: 8 },
  "Madagascar": { lat: -18.76, lng: 46.86, zoom: 5 },
  "Malasia": { lat: 4.21, lng: 101.97, zoom: 6 },
  "Mali": { lat: 17.57, lng: -3.99, zoom: 5 },
  "Malta": { lat: 35.93, lng: 14.37, zoom: 10 },
  "Marruecos": { lat: 31.79, lng: -7.09, zoom: 6 },
  "Mauritania": { lat: 21.0, lng: -10.94, zoom: 5 },
  "Mexico": { lat: 23.63, lng: -102.55, zoom: 4 },
  "Moldavia": { lat: 47.41, lng: 28.36, zoom: 8 },
  "Mongolia": { lat: 46.86, lng: 103.84, zoom: 4 },
  "Montenegro": { lat: 42.7, lng: 19.37, zoom: 8 },
  "Myanmar": { lat: 21.91, lng: 95.95, zoom: 5 },
  "Nepal": { lat: 28.39, lng: 84.12, zoom: 7 },
  "Nicaragua": { lat: 12.86, lng: -85.2, zoom: 7 },
  "Niger": { lat: 17.6, lng: 8.08, zoom: 5 },
  "Nigeria": { lat: 9.08, lng: 8.67, zoom: 6 },
  "Noruega": { lat: 60.47, lng: 8.46, zoom: 5 },
  "Nueva Caledonia": { lat: -22.27, lng: 166.45, zoom: 5 },
  "Nueva Zelanda": { lat: -40.9, lng: 174.88, zoom: 5 },
  "Oman": { lat: 21.51, lng: 55.92, zoom: 6 },
  "Países Bajos": { lat: 52.13, lng: 5.29, zoom: 7 },
  "Pakistan": { lat: 30.37, lng: 69.34, zoom: 5 },
  "Panama": { lat: 8.53, lng: -80.78, zoom: 7 },
  "Papua Nueva Guinea": { lat: -6.31, lng: 143.95, zoom: 6 },
  "Paraguay": { lat: -23.44, lng: -58.44, zoom: 6 },
  "Peru": { lat: -9.19, lng: -75.01, zoom: 5 },
  "Polonia": { lat: 51.91, lng: 19.14, zoom: 6 },
  "Portugal": { lat: 39.39, lng: -8.22, zoom: 6 },
  "PuertoRico": { lat: 18.22, lng: -66.59, zoom: 9 },
  "Qatar": { lat: 25.35, lng: 51.18, zoom: 8 },
  "Republica Checa": { lat: 49.81, lng: 15.47, zoom: 7 },
  "Republica del Congo": { lat: -0.22, lng: 15.82, zoom: 6 },
  "Republica Democratica del Congo": { lat: -4.03, lng: 21.75, zoom: 5 },
  "Republica Dominicana": { lat: 18.73, lng: -70.16, zoom: 8 },
  "Republica Centroafricana": { lat: 6.61, lng: 20.93, zoom: 6 },
  "Rumania": { lat: 45.94, lng: 24.96, zoom: 6 },
  "Rusia": { lat: 61.52, lng: 105.31, zoom: 3 },
  "Sahara Occidental": { lat: 24.21, lng: -12.88, zoom: 6 },
  "Senegal": { lat: 14.49, lng: -14.45, zoom: 7 },
  "Serbia": { lat: 44.01, lng: 21.0, zoom: 7 },
  "Sierra Leona": { lat: 8.46, lng: -11.78, zoom: 7 },
  "Singapur": { lat: 1.35, lng: 103.81, zoom: 11 },
  "Siria": { lat: 34.8, lng: 38.99, zoom: 6 },
  "SriLanka": { lat: 7.87, lng: 80.77, zoom: 7 },
  "Sudafrica": { lat: -30.55, lng: 22.93, zoom: 5 },
  "Sudan": { lat: 15.77, lng: 30.21, zoom: 5 },
  "Sudan del Sur": { lat: 6.87, lng: 31.3, zoom: 6 },
  "Suecia": { lat: 60.12, lng: 18.64, zoom: 5 },
  "Suiza": { lat: 46.81, lng: 8.22, zoom: 7 },
  "Surinam": { lat: 3.91, lng: -56.02, zoom: 7 },
  "Tailandia": { lat: 15.87, lng: 100.99, zoom: 5 },
  "Taiwan": { lat: 23.69, lng: 120.96, zoom: 7 },
  "Tanzania": { lat: -6.36, lng: 34.88, zoom: 5 },
  "Tayikistan": { lat: 38.86, lng: 71.27, zoom: 6 },
  "TimorOriental": { lat: -8.87, lng: 125.72, zoom: 8 },
  "Togo": { lat: 8.61, lng: 0.82, zoom: 7 },
  "Trinidad y Tobago": { lat: 10.69, lng: -61.22, zoom: 9 },
  "Tunez": { lat: 33.88, lng: 9.53, zoom: 6 },
  "Turkmenistan": { lat: 38.96, lng: 59.55, zoom: 5 },
  "Turquia": { lat: 38.96, lng: 35.24, zoom: 5 },
  "Ucrania": { lat: 48.37, lng: 31.16, zoom: 5 },
  "Uganda": { lat: 1.37, lng: 32.29, zoom: 7 },
  "Uruguay": { lat: -32.52, lng: -55.76, zoom: 7 },
  "Uzbekistan": { lat: 41.37, lng: 64.58, zoom: 5 },
  "Venezuela": { lat: 6.42, lng: -66.58, zoom: 5 },
  "Vietnam": { lat: 14.05, lng: 108.27, zoom: 5 },
  "Yemen": { lat: 15.55, lng: 48.51, zoom: 6 },
  "Zambia": { lat: -13.13, lng: 27.84, zoom: 6 },
  "Zimbabwe": { lat: -19.01, lng: 29.15, zoom: 6 }
};

export const codigosMoneda: Record<string, string> = {
  "USA": "USD",
  "Argentina": "ARS",
  "Brasil": "BRL",
  "Inglaterra": "GBP",
  "Canada": "CAD",
  "Australia": "AUD",
  "Chile": "CLP",
  "Mexico": "MXN",
  "China": "CNY",
  "Peru": "PEN",
  "Suecia": "SEK",
  "Nueva Zelanda": "NZD",
  "Rusia": "RUB",
  "India": "INR",
  "Sudafrica": "ZAR",
  "Dinamarca": "DKK",
  "Polonia": "PLN",
  "Republica Checa": "CZK",
  "Corea del Sur": "KRW",
  "Israel": "ILS",
  "Uruguay": "UYU",
  "Tailandia": "THB",
  "Emiratos Arabes Unidos": "AED",
  "Hungria": "HUF",
  "Colombia": "COP",
  "Paraguay": "PYG",
  "Venezuela": "VES",
  "Vietnam": "VND",
  "Iran": "IRR",
  "Bolivia": "BOB",
  "Armenia": "AMD",
  "CostaRica": "CRC",
  "Egipto": "EGP",
  "Argelia": "DZD",
  "Guatemala": "GTQ",
  "Guyana": "GYD",
  "Islandia": "ISK",
  "Bulgaria": "BGN",
  "Albania": "ALL",
  "Hong Kong": "HKD",
  "Ghana": "GHS",
  "Etiopia": "ETB",
  "Libano": "LBP",
  "Mongolia": "MNT",
  "Serbia": "RSD",
  "Nicaragua": "NIO",
  "Tunez": "TND",
  "Uganda": "UGX",
  "Suiza": "CHF",
  "Singapur": "SGD",
  "Nigeria": "NGN",
  "Japon": "JPY",
  "Sudan": "SDG",
  "Angola": "AOA",
  "Noruega": "NOK",
  "Ucrania": "UAH",
  "Rumania": "RON",
  "Kazajstan": "KZT",
  "Bielorrusia": "BYN",
  "Pakistan": "PKR",
  "Uzbekistan": "UZS",
  "Moldavia": "MDL",
  "Libia": "LYD",
  "Bosnia": "BAM",
  "Turkmenistan": "TMT",
  "Macedonia": "MKD",
  "Georgia": "GEL",
  "Azerbaiyan": "AZN",
  "Irak": "IQD",
  "Siria": "SYP",
  "Mauritania": "MRU",
  "Marruecos": "MAD",
  "Sahara Occidental": "MAD", // Usan Dirham Marroquí
  "Laos": "LAK",
  "Myanmar": "MMK",
  "Arabia Saudita": "SAR",
  "Belice": "BZD",
  "Honduras": "HNL",
  "Liberia": "LRD",
  "Surinam": "SRD",
  "Guinea": "GNF",
  "Namibia": "NAD",
  "Sierra Leona": "SLE",
  "Tanzania": "TZS",
  "Republica Democratica del Congo": "CDF",
  "Sudan del Sur": "SSP",
  "Mozambique": "MZN",
  "Kenya": "KES",
  "Madagascar": "MGA",
  "Zambia": "ZMW",
  "Botswana": "BWP",
  "Malawi": "MWK",
  "Somalia": "SOS",
  "Burundi": "BIF",
  "Eritrea": "ERN",
  "Lesoto": "LSL",
  "Indonesia": "IDR",
  "Yemen": "YER",
  "Oman": "OMR",
  "Nepal": "NPR",
  "Bangladesh": "BDT",
  "Camboya": "KHR",
  "Sri Lanka": "LKR",
  "Qatar": "QAR",
  "Tayikistan": "TJS",
  "Kirguistan": "KGS",
  "Filipinas": "PHP",
  "Malasia": "MYR",
  "Butan": "BTN",
  "Gambia": "GMD",
  "Esuatini": "SZL",
  "Ruanda": "RWF",
  "Papua Nueva Guinea": "PGK",
  "Taiwan": "TWD",
  "Vanuatu": "VUV",
  "Islas Salomon": "SBD",
  "Nueva Caledonia": "XPF",
  "Fiji": "FJD",
  "Djibouti": "DJF",
  "Somalilandia": "SLS",
  "Kuwait": "KWD",
  "Jordania": "JOD",
  "Bahamas": "BSD",
  "Jamaica": "JMD",
  "Republica Dominicana": "DOP",
  "Haiti": "HTG",
  "Cuba": "CUP",
  "Trinidad y Tobago": "TTD",
  "Corea del Norte": "KPW",
  "Islas Malvinas": "FKP",
  // Países Euro
  "Alemania": "EUR", "Austria": "EUR", "Belgica": "EUR", "Chipre": "EUR", "Croacia": "EUR", "Eslovaquia": "EUR", "Eslovenia": "EUR", "España": "EUR", "Estonia": "EUR", "Finlandia": "EUR", "Francia": "EUR", "Grecia": "EUR", "Irlanda": "EUR", "Italia": "EUR", "Letonia": "EUR", "Lituania": "EUR", "Luxemburgo": "EUR", "Malta": "EUR", "Países Bajos": "EUR", "Portugal": "EUR"
};