// Mapeo completo de nombres de países de inglés a español
export const nombresPaisesCompleto: Record<string, string> = {
  // América
  'United States of America': 'USA',
  'United States': 'USA',
  'USA': 'USA',
  'Canada': 'Canada',
  'Mexico': 'Mexico',
  'Brazil': 'Brasil',
  'Argentina': 'Argentina',
  'Chile': 'Chile',
  'Peru': 'Peru',
  'Colombia': 'Colombia',
  'Venezuela': 'Venezuela',
  'Ecuador': 'Ecuador',
  'Bolivia': 'Bolivia',
  'Paraguay': 'Paraguay',
  'Uruguay': 'Uruguay',
  'Costa Rica': 'CostaRica',
  'Panama': 'Panama',
  'El Salvador': 'El Salvador',
  'Guatemala': 'Guatemala',
  'Honduras': 'Honduras',
  'Nicaragua': 'Nicaragua',
  'Cuba': 'Cuba',
  'Jamaica': 'Jamaica',
  'Haiti': 'Haiti',
  'Dominican Republic': 'Dominicana',
  'Puerto Rico': 'USA',
  'Trinidad and Tobago': 'Trinidad y Tobago',
  'Barbados': 'Barbados',
  'Bahamas': 'Bahamas',
  'Belize': 'Belice',
  'Suriname': 'Surinam',
  'Guyana': 'Guyana',
  'French Guiana': 'Guyana Francesa',
  'Falkland Islands': 'Islas Malvinas',
  
  // Europa
  'United Kingdom': 'Inglaterra',
  'Great Britain': 'Inglaterra',
  'UK': 'Inglaterra',
  'England': 'Inglaterra',
  'Wales': 'Inglaterra',
  'Scotland': 'Inglaterra',
  'Northern Ireland': 'Inglaterra',
  'Spain': 'España',
  'France': 'Francia',
  'Germany': 'Alemania',
  'Italy': 'Italia',
  'Portugal': 'Portugal',
  'Netherlands': 'Países Bajos',
  'Belgium': 'Belgica',
  'Switzerland': 'Suiza',
  'Austria': 'Austria',
  'Greece': 'Grecia',
  'Poland': 'Polonia',
  'Czech Republic': 'Republica Checa',
  'Czechia': 'Republica Checa',
  'Slovakia': 'Eslovaquia',
  'Slovenia': 'Eslovenia',
  'Croatia': 'Croacia',
  'Serbia': 'Serbia',
  'Republic of Serbia': 'Serbia',
  'Srbija': 'Serbia',
  'Bosnia and Herzegovina': 'Bosnia',
  'Montenegro': 'Montenegro',
  'Albania': 'Albania',
  'Macedonia': 'Macedonia',
  'North Macedonia': 'Macedonia',
  'Bulgaria': 'Bulgaria',
  'Romania': 'Rumania',
  'Hungary': 'Hungria',
  'Finland': 'Finlandia',
  'Sweden': 'Suecia',
  'Norway': 'Noruega',
  'Denmark': 'Dinamarca',
  'Iceland': 'Islandia',
  'Ireland': 'Irlanda',
  'Estonia': 'Estonia',
  'Latvia': 'Letonia',
  'Lithuania': 'Lituania',
  'Belarus': 'Bielorrusia',
  'Ukraine': 'Ucrania',
  'Moldova': 'Moldavia',
  'Russia': 'Rusia',
  'Russian Federation': 'Rusia',
  'Cyprus': 'Chipre',
  'Malta': 'Malta',
  'Luxembourg': 'Luxemburgo',
  'Kosovo': 'Kosovo',
  'Armenia': 'Armenia',
  'Georgia': 'Georgia',
  'Azerbaijan': 'Azerbaiyan',
  'Turkey': 'Turquia',
  
  // Asia
  'China': 'China',
  'Japan': 'Japon',
  'South Korea': 'Corea del Sur',
  'Republic of Korea': 'Corea del Sur',
  'North Korea': 'Corea del Norte',
  'India': 'India',
  'Pakistan': 'Pakistan',
  'Bangladesh': 'Bangladesh',
  'Afghanistan': 'Afganistan',
  'Iran': 'Iran',
  'Iraq': 'Irak',
  'Saudi Arabia': 'Arabia Saudita',
  'United Arab Emirates': 'Emiratos Arabes Unidos',
  'UAE': 'Emiratos Arabes Unidos',
  'Yemen': 'Yemen',
  'Oman': 'Oman',
  'Qatar': 'Qatar',
  'Kuwait': 'Kuwait',
  'Bahrain': 'Bahrain',
  'Israel': 'Israel',
  'Palestine': 'Palestina',
  'Jordan': 'Jordania',
  'Lebanon': 'Libano',
  'Syria': 'Siria',
  'Thailand': 'Tailandia',
  'Vietnam': 'Vietnam',
  'Philippines': 'Filipinas',
  'Indonesia': 'Indonesia',
  'Malaysia': 'Malasia',
  'Singapore': 'Singapur',
  'Myanmar': 'Myanmar',
  'Burma': 'Myanmar',
  'Cambodia': 'Camboya',
  'Laos': 'Laos',
  'Nepal': 'Nepal',
  'Bhutan': 'Butan',
  'Sri Lanka': 'Sri Lanka',
  'Mongolia': 'Mongolia',
  'Kazakhstan': 'Kazajstan',
  'Uzbekistan': 'Uzbekistan',
  'Turkmenistan': 'Turkmenistan',
  'Tajikistan': 'Tajikistan',
  'Kyrgyzstan': 'Kyrgyzstan',
  'Hong Kong': 'Hong Kong',
  'Taiwan': 'Taiwan',
  'Timor-Leste': 'Timor Oriental',
  'East Timor': 'Timor Oriental',
  'Brunei': 'Brunei',
  
  // África
  'Egypt': 'Egipto',
  'South Africa': 'Sudafrica',
  'Nigeria': 'Nigeria',
  'Kenya': 'Kenya',
  'Ghana': 'Ghana',
  'Morocco': 'Marruecos',
  'Algeria': 'Argelia',
  'Tunisia': 'Tunez',
  'Libya': 'Libia',
  'Sudan': 'Sudan',
  'South Sudan': 'Sudan del Sur',
  'Ethiopia': 'Etiopia',
  'Somalia': 'Somalia',
  'Eritrea': 'Eritrea',
  'Djibouti': 'Djibouti',
  'Tanzania': 'Tanzania',
  'United Republic of Tanzania': 'Tanzania',
  'Uganda': 'Uganda',
  'Rwanda': 'Ruanda',
  'Burundi': 'Burundi',
  'Democratic Republic of the Congo': 'Republica Democratica del Congo',
  'DRC': 'Republica Democratica del Congo',
  'Republic of the Congo': 'Republica del Congo',
  'Congo': 'Republica del Congo',
  'Angola': 'Angola',
  'Zambia': 'Zambia',
  'Zimbabwe': 'Zimbabwe',
  'Mozambique': 'Mozambique',
  'Madagascar': 'Madagascar',
  'Malawi': 'Malawi',
  'Botswana': 'Botswana',
  'Namibia': 'Namibia',
  'Swaziland': 'Esuatini',
  'Eswatini': 'Esuatini',
  'Lesotho': 'Lesoto',
  'Cameroon': 'Camerun',
  'Central African Republic': 'Republica Centroafricana',
  'Chad': 'Chad',
  'Niger': 'Niger',
  'Mali': 'Mali',
  'Burkina Faso': 'Burkina Faso',
  'Senegal': 'Senegal',
  'Gambia': 'Gambia',
  'Guinea': 'Guinea',
  'Guinea-Bissau': 'Guinea Bissau',
  'Sierra Leone': 'Sierra Leona',
  'Liberia': 'Liberia',
  'Ivory Coast': 'Costa de Marfil',
  "Côte d'Ivoire": 'Costa de Marfil',
  'Togo': 'Togo',
  'Benin': 'Benin',
  'Gabon': 'Gabon',
  'Equatorial Guinea': 'Guinea Ecuatorial',
  'Mauritania': 'Mauritania',
  'Cape Verde': 'Cabo Verde',
  'Comoros': 'Comoras',
  'Seychelles': 'Seychelles',
  'Mauritius': 'Mauricio',
  'Somaliland': 'Somaliland',
  // Oceanía
  'Australia': 'Australia',
  'New Zealand': 'Nueva Zelanda',
  'Papua New Guinea': 'Papua Nueva Guinea',
  'Fiji': 'Fiji',
  'Solomon Islands': 'Islas Salomon',
  'Vanuatu': 'Vanuatu',
  'Nueva Caledonia': 'Nueva Caledonia',
  'Samoa': 'Samoa',
  'Tonga': 'Tonga',
  "Western Sahara": "Sahara Occidental",
  
  // Territorios especiales
  'Greenland': 'Dinamarca',
  'French Southern and Antarctic Lands': 'Tierras Australes y Antárticas Francesas',
  'Northern Cyprus': 'Chipre del Norte',
};

// Lista de todos los países que tienen billetes en el sistema
export const paisesConBilletes = [
  // Europa - Países Euro
  'Alemania', 'Austria', 'Belgica', 'Chipre', 'Croacia', 'Eslovaquia',
  'Eslovenia', 'España', 'Estonia', 'Finlandia', 'Francia', 'Grecia',
  'Irlanda', 'Italia', 'Kosovo', 'Letonia', 'Lituania', 'Luxemburgo',
  'Malta', 'Montenegro', 'Países Bajos', 'Portugal',
  
  // África - Países CFA Occidental
  'Benin', 'Burkina Faso', 'Costa de Marfil', 'Guinea Bissau',
  'Mali', 'Niger', 'Senegal', 'Togo',
  
  // África - Países CFA Central
  'Camerun', 'Chad', 'Gabon', 'Guinea Ecuatorial',
  'Republica Centroafricana', 'Republica del Congo',
  
  // Países con Dólar US
  'USA', 'Ecuador', 'Panama', 'El Salvador',
  'Puerto Rico', 'Zimbabwe', 'Timor Oriental',
  
  // Países con Lira Turca
  'Turquia', 'Chipre del Norte',
  
  // América
  'Argentina', 'Brasil', 'Canada', 'Chile', 'Colombia', 'Mexico',
  'Peru', 'Uruguay', 'Venezuela', 'Bolivia', 'Paraguay',
  'CostaRica', 'Guatemala', 'Honduras', 'Nicaragua',
  'Jamaica', 'Dominicana', 'Haiti', 'Cuba',
  'Trinidad y Tobago', 'Bahamas', 'Barbados', 'Belice',
  'Surinam', 'Guyana',
  
  // Europa (no Euro)
  'Inglaterra', 'Suiza', 'Noruega', 'Suecia', 'Dinamarca',
  'Polonia', 'Republica Checa', 'Hungria', 'Rumania',
  'Bulgaria', 'Serbia', 'Bosnia', 'Albania', 'Macedonia',
  'Islandia', 'Rusia', 'Ucrania', 'Bielorrusia', 'Moldavia',
  'Georgia', 'Armenia', 'Azerbaiyan',
  
  // Asia
  'China', 'Japon', 'Corea del Sur', 'Corea del Norte',
  'India', 'Pakistan', 'Bangladesh', 'Afganistan',
  'Iran', 'Irak', 'Arabia Saudita', 'Emiratos Arabes Unidos',
  'Kuwait', 'Qatar', 'Bahrain', 'Oman', 'Yemen',
  'Israel', 'Jordania', 'Libano', 'Siria',
  'Tailandia', 'Vietnam', 'Filipinas', 'Indonesia',
  'Malasia', 'Singapur', 'Myanmar', 'Camboya', 'Laos',
  'Nepal', 'Butan', 'Sri Lanka', 'Mongolia',
  'Kazajstan', 'Uzbekistan', 'Turkmenistan', 'Tajikistan',
  'Kyrgyzstan', 'Hong Kong', 'Taiwan', 'Brunei',
  
  // África (no CFA)
  'Egipto', 'Sudafrica', 'Nigeria', 'Kenya', 'Ghana',
  'Marruecos', 'Argelia', 'Tunez', 'Libia',
  'Sudan', 'Sudan del Sur', 'Etiopia', 'Somalia',
  'Eritrea', 'Djibouti', 'Tanzania', 'Uganda',
  'Ruanda', 'Burundi', 'Republica Democratica del Congo',
  'Angola', 'Zambia', 'Mozambique', 'Madagascar',
  'Malawi', 'Botswana', 'Namibia', 'Esuatini', 'Lesoto',
  'Gambia', 'Guinea', 'Sierra Leona', 'Liberia',
  'Mauritania', 'Cabo Verde', 'Comoras', 'Seychelles',
  'Mauricio', 'Somaliland', "Sahara Occidental",
  
  // Oceanía
  'Australia', 'Nueva Zelanda', 'Papua Nueva Guinea',
  'Fiji', 'Islas Salomon', 'Vanuatu', 'Nueva Caledonia',
  'Samoa', 'Tonga',
  
  // Territorios especiales
  'Islas Malvinas',
  'Tierras Australes y Antárticas Francesas',
  'Guyana Francesa'
];
