import { todosLosBilletes } from './billetes-data/index';

// Mapeo completo de nombres de países de inglés a español
export const nombresPaisesCompleto: Record<string, string> = {
  // América
  'United States of America': 'USA',
  'United States': 'USA',
  'USA': 'USA',
  'Canada': 'Canada',
  'Mexico': 'Mexico',
  'Brazil': 'Brasil',
  'Argentina': 'Argentina',
  'Chile': 'Chile',
  'Peru': 'Peru',
  'Colombia': 'Colombia',
  'Venezuela': 'Venezuela',
  'Ecuador': 'Ecuador',
  'Bolivia': 'Bolivia',
  'Paraguay': 'Paraguay',
  'Uruguay': 'Uruguay',
  'Costa Rica': 'CostaRica',
  'Panama': 'Panama',
  'El Salvador': 'ElSalvador',
  'Guatemala': 'Guatemala',
  'Honduras': 'Honduras',
  'Nicaragua': 'Nicaragua',
  'Cuba': 'Cuba',
  'Jamaica': 'Jamaica',
  'Haiti': 'Haiti',
  'Dominican Republic': 'Dominicana',
  'Puerto Rico': 'USA',
  'Trinidad and Tobago': 'Trinidad y Tobago',
  'Barbados': 'Barbados',
  'Bahamas': 'Bahamas',
  'Belize': 'Belice',
  'Suriname': 'Surinam',
  'Guyana': 'Guyana',
  'French Guiana': 'Guyana Francesa',
  'Falkland Islands': 'Islas Malvinas',
  
  // Europa
  'United Kingdom': 'Inglaterra',
  'Great Britain': 'Inglaterra',
  'UK': 'Inglaterra',
  'England': 'Inglaterra',
  'Wales': 'Inglaterra',
  'Scotland': 'Inglaterra',
  'Northern Ireland': 'Inglaterra',
  'Spain': 'España',
  'France': 'Francia',
  'Germany': 'Alemania',
  'Italy': 'Italia',
  'Portugal': 'Portugal',
  'Netherlands': 'Países Bajos',
  'Belgium': 'Belgica',
  'Switzerland': 'Suiza',
  'Austria': 'Austria',
  'Greece': 'Grecia',
  'Poland': 'Polonia',
  'Czech Republic': 'Republica Checa',
  'Czechia': 'Republica Checa',
  'Slovakia': 'Eslovaquia',
  'Slovenia': 'Eslovenia',
  'Croatia': 'Croacia',
  'Serbia': 'Serbia',
  'Republic of Serbia': 'Serbia',
  'Srbija': 'Serbia',
  'Bosnia and Herzegovina': 'Bosnia',
  'Montenegro': 'Montenegro',
  'Albania': 'Albania',
  'Macedonia': 'Macedonia',
  'North Macedonia': 'Macedonia',
  'Bulgaria': 'Bulgaria',
  'Romania': 'Rumania',
  'Hungary': 'Hungria',
  'Finland': 'Finlandia',
  'Sweden': 'Suecia',
  'Norway': 'Noruega',
  'Denmark': 'Dinamarca',
  'Iceland': 'Islandia',
  'Ireland': 'Irlanda',
  'Estonia': 'Estonia',
  'Latvia': 'Letonia',
  'Lithuania': 'Lituania',
  'Belarus': 'Bielorrusia',
  'Ukraine': 'Ucrania',
  'Moldova': 'Moldavia',
  'Russia': 'Rusia',
  'Russian Federation': 'Rusia',
  'Cyprus': 'Chipre',
  'Malta': 'Malta',
  'Luxembourg': 'Luxemburgo',
  'Kosovo': 'Kosovo',
  'Armenia': 'Armenia',
  'Georgia': 'Georgia',
  'Azerbaijan': 'Azerbaiyan',
  'Turkey': 'Turquia',
  
  // Asia
  'China': 'China',
  'Japan': 'Japon',
  'South Korea': 'Corea del Sur',
  'Republic of Korea': 'Corea del Sur',
  'North Korea': 'Corea del Norte',
  'India': 'India',
  'Pakistan': 'Pakistan',
  'Bangladesh': 'Bangladesh',
  'Afghanistan': 'Afganistan',
  'Iran': 'Iran',
  'Iraq': 'Irak',
  'Saudi Arabia': 'Arabia Saudita',
  'United Arab Emirates': 'Emiratos Arabes Unidos',
  'UAE': 'Emiratos Arabes Unidos',
  'Yemen': 'Yemen',
  'Oman': 'Oman',
  'Qatar': 'Qatar',
  'Kuwait': 'Kuwait',
  'Bahrain': 'Bahrain',
  'Israel': 'Israel',
  'Palestine': 'Palestina',
  'Jordan': 'Jordania',
  'Lebanon': 'Libano',
  'Syria': 'Siria',
  'Thailand': 'Tailandia',
  'Vietnam': 'Vietnam',
  'Philippines': 'Filipinas',
  'Indonesia': 'Indonesia',
  'Malaysia': 'Malasia',
  'Singapore': 'Singapur',
  'Myanmar': 'Myanmar',
  'Burma': 'Myanmar',
  'Cambodia': 'Camboya',
  'Laos': 'Laos',
  'Nepal': 'Nepal',
  'Bhutan': 'Butan',
  'Sri Lanka': 'Sri Lanka',
  'Mongolia': 'Mongolia',
  'Kazakhstan': 'Kazajstan',
  'Uzbekistan': 'Uzbekistan',
  'Turkmenistan': 'Turkmenistan',
  'Tajikistan': 'Tajikistan',
  'Kyrgyzstan': 'Kyrgyzstan',
  'Hong Kong': 'Hong Kong',
  'Taiwan': 'Taiwan',
  'Timor-Leste': 'TimorOriental',
  'East Timor': 'TimorOriental',
  'Brunei': 'Brunei',
  
  // África
  'Egypt': 'Egipto',
  'South Africa': 'Sudafrica',
  'Nigeria': 'Nigeria',
  'Kenya': 'Kenya',
  'Ghana': 'Ghana',
  'Morocco': 'Marruecos',
  'Algeria': 'Argelia',
  'Tunisia': 'Tunez',
  'Libya': 'Libia',
  'Sudan': 'Sudan',
  'South Sudan': 'Sudan del Sur',
  'Ethiopia': 'Etiopia',
  'Somalia': 'Somalia',
  'Eritrea': 'Eritrea',
  'Djibouti': 'Djibouti',
  'Tanzania': 'Tanzania',
  'United Republic of Tanzania': 'Tanzania',
  'Uganda': 'Uganda',
  'Rwanda': 'Ruanda',
  'Burundi': 'Burundi',
  'Democratic Republic of the Congo': 'Republica Democratica del Congo',
  'DRC': 'Republica Democratica del Congo',
  'Republic of the Congo': 'Republica del Congo',
  'Congo': 'Republica del Congo',
  'Angola': 'Angola',
  'Zambia': 'Zambia',
  'Zimbabwe': 'Zimbabwe',
  'Mozambique': 'Mozambique',
  'Madagascar': 'Madagascar',
  'Malawi': 'Malawi',
  'Botswana': 'Botswana',
  'Namibia': 'Namibia',
  'Swaziland': 'Esuatini',
  'Eswatini': 'Esuatini',
  'Lesotho': 'Lesoto',
  'Cameroon': 'Camerun',
  'Central African Republic': 'Republica Centroafricana',
  'Chad': 'Chad',
  'Niger': 'Niger',
  'Mali': 'Mali',
  'Burkina Faso': 'Burkina Faso',
  'Senegal': 'Senegal',
  'Gambia': 'Gambia',
  'Guinea': 'Guinea',
  'Guinea-Bissau': 'Guinea Bissau',
  'Sierra Leone': 'Sierra Leona',
  'Liberia': 'Liberia',
  'Ivory Coast': 'Costa de Marfil',
  "Côte d'Ivoire": 'Costa de Marfil',
  'Togo': 'Togo',
  'Benin': 'Benin',
  'Gabon': 'Gabon',
  'Equatorial Guinea': 'Guinea Ecuatorial',
  'Mauritania': 'Mauritania',
  'Cape Verde': 'Cabo Verde',
  'Comoros': 'Comoras',
  'Seychelles': 'Seychelles',
  'Mauritius': 'Mauricio',
  'Somaliland': 'Somaliland',
  // Oceanía
  'Australia': 'Australia',
  'New Zealand': 'Nueva Zelanda',
  'Papua New Guinea': 'Papua Nueva Guinea',
  'Fiji': 'Fiji',
  'Solomon Islands': 'Islas Salomon',
  'Vanuatu': 'Vanuatu',
  'New Caledonia': 'Nueva Caledonia',
  'Samoa': 'Samoa',
  'Tonga': 'Tonga',
  "Western Sahara": "Sahara Occidental",
  
  // Territorios especiales
  'Greenland': 'Dinamarca',
  'French Southern and Antarctic Lands': 'Tierras Australes y Antárticas Francesas',
  'Northern Cyprus': 'Chipre del Norte',
};

// Lista generada automáticamente a partir de los datos reales de billetes
export const paisesConBilletes = Object.keys(todosLosBilletes);
